#!/usr/bin/env node

/**
 * env-sync.js — SouthZone Environment Synchronizer
 * 
 * Reads the root .env MODE toggle and generates:
 *   - frontend/.env  (Next.js client vars)
 *   - backend/.env   (Express server vars)
 * 
 * Usage:
 *   node env-sync.js          → Reads MODE from root .env
 *   node env-sync.js local    → Force local mode
 *   node env-sync.js global   → Force global mode
 */

const fs = require('fs');
const path = require('path');

// ─── Parse .env file into key-value object ───
function parseEnv(filePath) {
  const content = fs.readFileSync(filePath, 'utf-8');
  const vars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    vars[key] = value;
  }
  return vars;
}

// ─── Main ───
const rootDir = __dirname;
const rootEnvPath = path.join(rootDir, '.env');

if (!fs.existsSync(rootEnvPath)) {
  console.error('❌ Root .env file not found at:', rootEnvPath);
  process.exit(1);
}

const env = parseEnv(rootEnvPath);

// Allow CLI override: node env-sync.js local | global
const cliMode = process.argv[2];
const mode = (cliMode || env.MODE || 'local').toLowerCase();

if (mode !== 'local' && mode !== 'global') {
  console.error('❌ Invalid MODE:', mode, '— Must be "local" or "global"');
  process.exit(1);
}

const isLocal = mode === 'local';

// Resolve URLs based on mode
const backendUrl = isLocal ? (env.LOCAL_BACKEND_URL || 'http://localhost:5000/api') : (env.GLOBAL_BACKEND_URL || env.LOCAL_BACKEND_URL);
const frontendUrl = isLocal ? (env.LOCAL_FRONTEND_URL || 'http://localhost:3000') : (env.GLOBAL_FRONTEND_URL || env.LOCAL_FRONTEND_URL);
const nodeEnv = isLocal ? 'development' : 'production';

// ═══ Generate frontend/.env ═══
const frontendEnv = `# ═══ AUTO-GENERATED by env-sync.js ═══
# Mode: ${mode.toUpperCase()} | Generated: ${new Date().toLocaleString()}
# Do NOT edit manually — edit root .env and run: node env-sync.js
# ═══════════════════════════════════════

NEXT_PUBLIC_API_URL=${backendUrl}
NEXT_PUBLIC_RAZORPAY_KEY_ID=${env.RAZORPAY_KEY_ID || 'rzp_test_ShPCY9vwVFgWgq'}
NEXT_PUBLIC_OTP_VERI=${env.OTP_VERI || 'OFF'}
`;

// ═══ Generate backend/.env ═══
const backendEnv = `# ═══ AUTO-GENERATED by env-sync.js ═══
# Mode: ${mode.toUpperCase()} | Generated: ${new Date().toLocaleString()}
# Do NOT edit manually — edit root .env and run: node env-sync.js
# ═══════════════════════════════════════

# Server Configuration
NODE_ENV=${nodeEnv}
PORT=5000

# Database Configuration
DB_HOST=${env.DB_HOST || 'localhost'}
DB_PORT=${env.DB_PORT || '5432'}
DB_USER=${env.DB_USER || 'postgres'}
DB_PASSWORD=${env.DB_PASSWORD || 'root'}
DB_NAME=${env.DB_NAME || 'SZ'}

# Redis Configuration
REDIS_HOST=${env.REDIS_HOST || 'localhost'}
REDIS_PORT=${env.REDIS_PORT || '6379'}

# JWT Configuration
JWT_SECRET=${env.JWT_SECRET}
JWT_REFRESH_SECRET=${env.JWT_REFRESH_SECRET}
JWT_EXPIRES_IN=${env.JWT_EXPIRES_IN || '7d'}

# Rate Limiting
RATE_LIMIT=${isLocal ? 'OFF' : 'ON'}
API_RATE_LIMIT_MAX=${env.API_RATE_LIMIT_MAX || '1000'}
AUTH_RATE_LIMIT_MAX=${env.AUTH_RATE_LIMIT_MAX || '20'}

# Razorpay Configuration
RAZORPAY_KEY_ID=${env.RAZORPAY_KEY_ID}
RAZORPAY_KEY_SECRET=${env.RAZORPAY_KEY_SECRET}

# Email Configuration
RESEND_API_KEY=${env.RESEND_API_KEY}
EMAIL_HOST=${env.EMAIL_HOST || 'smtp.gmail.com'}
EMAIL_PORT=${env.EMAIL_PORT || '587'}
EMAIL_USER=${env.EMAIL_USER}
EMAIL_PASS=${env.EMAIL_PASS}
EMAIL_FROM=SouthZone <${env.EMAIL_USER}>

# Cloudinary Configuration
CLOUDINARY_CLOUD_NAME=${env.CLOUDINARY_CLOUD_NAME}
CLOUDINARY_API_KEY=${env.CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET=${env.CLOUDINARY_API_SECRET}

# WhatsApp Cloud API
WHATSAPP_ACCESS_TOKEN=${env.WHATSAPP_ACCESS_TOKEN}
WHATSAPP_PHONE_NUMBER_ID=${env.WHATSAPP_PHONE_NUMBER_ID}
WHATSAPP_BUSINESS_ACCOUNT_ID=${env.WHATSAPP_BUSINESS_ACCOUNT_ID}

# Security Toggle
OTP_VERI=${env.OTP_VERI || 'OFF'}

# Frontend URL (for CORS)
FRONTEND_URL=${frontendUrl}

# Google OAuth
GOOGLE_CLIENT_ID=${env.GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${env.GOOGLE_CLIENT_SECRET}
`;

// ─── Write files ───
const frontendPath = path.join(rootDir, 'frontend', '.env');
const backendPath = path.join(rootDir, 'backend', '.env');

fs.writeFileSync(frontendPath, frontendEnv, 'utf-8');
fs.writeFileSync(backendPath, backendEnv, 'utf-8');

// ─── Output ───
const modeLabel = isLocal ? '🏠 LOCAL' : '🌐 GLOBAL';
const modeColor = isLocal ? '\x1b[36m' : '\x1b[35m';
const reset = '\x1b[0m';
const bold = '\x1b[1m';
const dim = '\x1b[2m';
const green = '\x1b[32m';

console.log('');
console.log(`${bold}═══════════════════════════════════════════${reset}`);
console.log(`${bold}  SouthZone Environment Sync${reset}`);
console.log(`${bold}═══════════════════════════════════════════${reset}`);
console.log('');
console.log(`  ${bold}Mode:${reset}      ${modeColor}${modeLabel}${reset}`);
console.log(`  ${bold}API URL:${reset}   ${dim}${backendUrl}${reset}`);
console.log(`  ${bold}Frontend:${reset}  ${dim}${frontendUrl}${reset}`);
console.log(`  ${bold}NODE_ENV:${reset}  ${dim}${nodeEnv}${reset}`);
console.log(`  ${bold}Rate Limit:${reset} ${dim}${isLocal ? 'OFF' : 'ON'}${reset}`);
console.log('');
console.log(`  ${green}✔${reset} frontend/.env updated`);
console.log(`  ${green}✔${reset} backend/.env  updated`);
console.log('');
console.log(`${dim}  Restart your dev servers to apply changes.${reset}`);
console.log('');
